Algoritmo "idades"

Var

nomeA, nomeB: caractere

idadeA, idadeB: inteiro

media: real

Inicio

escreval("Dados da primeira pessoa: ")
escreva("Nome: ")
leia(nomeA)
escreva("Idade: ")
leia(idadeA)
escreval("Dados da Segunda pessoa: ")
escreva("Nome: ")
leia(nomeB)
escreva("Idade: ")
leia(idadeB)
media <- (idadeA + idadeB)/2
escreval("A idade média de ",nomeA," e ",nomeB," é de ",media:4:1," anos ")
Fimalgoritmo