Algoritmo "terreno"

Var
largura, comprimento, valor, resultado : real


Inicio
escreva("Digite a largura do terreno: ")
leia(largura)

escreva("Digite o comprimento do terreno: ")
leia(comprimento)

escreva("Digite o valor do metro quadrado: ")
leia(valor)

resultado <-  (largura * comprimento)

escreval("Area do terreno = ", resultado:4:2)

escreva("Preco do terreno = ", (resultado * valor):4:2)






Fimalgoritmo